#Prerequisite

In [ ]:
!pip install scikit-learn-intelex

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.2/136.2 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.2/75.2 MB 10.7 MB/s eta 0:00:00


In [ ]:
import os
import numpy as np
import pandas as pd
from numpy import mean
from numpy import std
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score

In [ ]:
#from google.colab import drive
!gdown 1d-n3DRMh8YZwAd5pxryRZMiqLKH4dPPo
!gdown 1GzBgV34sITnhenBS-E21ZvQ9MU8SwMMa
#drive.mount('/content/drive')

Downloading...
From: https://drive.google.com/uc?id=1d-n3DRMh8YZwAd5pxryRZMiqLKH4dPPo
To: /content/labels1.csv
100% 3.89k/3.89k [00:00<00:00, 17.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GzBgV34sITnhenBS-E21ZvQ9MU8SwMMa
To: /content/data1.csv
100% 824M/824M [00:10<00:00, 75.7MB/s]


In [ ]:
data = pd.read_csv("/content/data1.csv")

In [ ]:
labels = pd.read_csv("/content/labels1.csv")

In [ ]:
data.info

<bound method DataFrame.info of                         Unnamed: 0  ENSG00000000003.15  ENSG00000000005.6  \
0     TCGA-AJ-A3NH-11A-11R-A22K-07            1.565076           0.066810   
1     TCGA-AX-A05Y-11A-11R-A27V-07            0.975542           0.159958   
2     TCGA-FL-A1YN-11A-11R-A32Y-07            1.277174           0.058654   
3     TCGA-FL-A1YU-11A-11R-A32Y-07            1.319747           0.039811   
4     TCGA-AJ-A3NC-11A-11R-A22K-07            1.017179           0.158393   
...                            ...                 ...                ...   
1292  TCGA-JY-A93C-01A-11R-A38D-31            1.536423           0.003977   
1293  TCGA-JY-A6FH-01A-11R-A336-31            0.789686           0.003762   
1294  TCGA-L5-A8NF-01A-11R-A37I-31            0.755745           0.000000   
1295  TCGA-VR-AA4D-01A-11R-A37I-31            1.252630           0.007961   
1296  TCGA-IG-A3QL-01A-11R-A24K-31            1.400346           0.003331   

      ENSG00000000419.13  ENSG00000000457.1

In [ ]:
labels.info

<bound method DataFrame.info of       0
0     0
1     0
2     0
3     0
4     0
...  ..
1291  4
1292  4
1293  4
1294  4
1295  4

[1296 rows x 1 columns]>

In [ ]:
columns_to_remove = []
for i in range(len(data.columns)):
  if(data.columns[i].find("Unnamed")>=0):
    columns_to_remove.append(data.columns[i])
data = data.drop(labels = columns_to_remove, axis = 1, inplace = False)

# this removes any row that has even a single null value
#data = data.dropna()

# To remove only the rows where all values are null
#data = data.dropna(how='all')

# Remove rows with null values only in the 'column_name' column
#data = data.dropna(subset=['column_name'])

In [ ]:
X = data.values
y = labels.values
X = X[:-1]
print("(Dataset) (Label):",X.shape,y.shape)

(Dataset) (Label): (1296, 60660) (1296, 1)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state =7, shuffle = True, stratify = y)
# We need random_state so that using that same seed, we can reproduce the exact same results later
# We need startify to balance the split. Else, the train data might have too many values of a particular class,
# and too less value of another class. This can later on create overfitting or underfitting

# Print dimension of training/test dataset and labels.
print("Train Set: ",X_train.shape,y_train.shape)
print("Test Set: ",X_test.shape,y_test.shape)

Train Set:  (1036, 60660) (1036, 1)
Test Set:  (260, 60660) (260, 1)


In [ ]:
# Normalize Standardize features by removing the mean and scaling to unit variance.

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

#Logistic Regression

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Initialize the Logistic Regression model
modelLR = LogisticRegression(max_iter=1000, C=20, penalty="l2", random_state=17, solver="lbfgs")
fit = modelLR.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = modelLR.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

NameError: ignored

#Decision Tree

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.tree import DecisionTreeClassifier

# Initialize the Logistic Regression model
modelDT = DecisionTreeClassifier(random_state = 17)
fit = modelDT.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = modelDT.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Accuracy: 95.38%
Macro Precision: 0.9271
Weighted Precision: 0.9541
Macro Recall: 0.9420
Weighted Recall: 0.9538
Macro F1-Score: 0.9341
Weighted F1-Score: 0.9537

Confusion Matrix:
[[ 20   1   0   3   1]
 [  2 107   0   0   2]
 [  0   0  13   0   0]
 [  1   0   1  72   0]
 [  1   0   0   0  36]]

Classification Report:
              precision    recall  f1-score   support

           0     0.8333    0.8000    0.8163        25
           1     0.9907    0.9640    0.9772       111
           2     0.9286    1.0000    0.9630        13
           3     0.9600    0.9730    0.9664        74
           4     0.9231    0.9730    0.9474        37

    accuracy                         0.9538       260
   macro avg     0.9271    0.9420    0.9341       260
weighted avg     0.9541    0.9538    0.9537       260



#Random Forest

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.ensemble import RandomForestClassifier

# Initialize the Logistic Regression model
modelRF = RandomForestClassifier(n_estimators = 500, criterion="entropy", min_samples_split = 2, min_samples_leaf= 1, max_features = 'sqrt', max_depth= 50, bootstrap=False, n_jobs=-1)
fit = modelRF.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = modelRF.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Accuracy: 98.46%
Macro Precision: 0.9671
Weighted Precision: 0.9851
Macro Recall: 0.9786
Weighted Recall: 0.9846
Macro F1-Score: 0.9723
Weighted F1-Score: 0.9846

Confusion Matrix:
[[ 23   0   0   0   2]
 [  0 111   0   0   0]
 [  0   0  13   0   0]
 [  1   0   1  72   0]
 [  0   0   0   0  37]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9583    0.9200    0.9388        25
           1     1.0000    1.0000    1.0000       111
           2     0.9286    1.0000    0.9630        13
           3     1.0000    0.9730    0.9863        74
           4     0.9487    1.0000    0.9737        37

    accuracy                         0.9846       260
   macro avg     0.9671    0.9786    0.9723       260
weighted avg     0.9851    0.9846    0.9846       260



#KNN

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.neighbors import KNeighborsClassifier

# Initialize the Logistic Regression model
model_KNN = KNeighborsClassifier (n_neighbors = 7)
fit = model_KNN.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = model_KNN.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Accuracy: 95.77%
Macro Precision: 0.9274
Weighted Precision: 0.9643
Macro Recall: 0.9659
Weighted Recall: 0.9577
Macro F1-Score: 0.9432
Weighted F1-Score: 0.9588

Confusion Matrix:
[[ 24   0   0   0   1]
 [  0 110   0   1   0]
 [  0   0  13   0   0]
 [  8   0   1  65   0]
 [  0   0   0   0  37]]

Classification Report:
              precision    recall  f1-score   support

           0     0.7500    0.9600    0.8421        25
           1     1.0000    0.9910    0.9955       111
           2     0.9286    1.0000    0.9630        13
           3     0.9848    0.8784    0.9286        74
           4     0.9737    1.0000    0.9867        37

    accuracy                         0.9577       260
   macro avg     0.9274    0.9659    0.9432       260
weighted avg     0.9643    0.9577    0.9588       260



#Gradient Boosting

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score


from xgboost import XGBClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Initialize the Logistic Regression model
model_XGBoost = XGBClassifier()

fit = model_XGBoost.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = model_XGBoost.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Accuracy: 98.46%
Macro Precision: 0.9671
Weighted Precision: 0.9851
Macro Recall: 0.9786
Weighted Recall: 0.9846
Macro F1-Score: 0.9723
Weighted F1-Score: 0.9846

Confusion Matrix:
[[ 23   0   0   0   2]
 [  0 111   0   0   0]
 [  0   0  13   0   0]
 [  1   0   1  72   0]
 [  0   0   0   0  37]]

Classification Report:
              precision    recall  f1-score   support

           0     0.9583    0.9200    0.9388        25
           1     1.0000    1.0000    1.0000       111
           2     0.9286    1.0000    0.9630        13
           3     1.0000    0.9730    0.9863        74
           4     0.9487    1.0000    0.9737        37

    accuracy                         0.9846       260
   macro avg     0.9671    0.9786    0.9723       260
weighted avg     0.9851    0.9846    0.9846       260



#Support Vector Machine

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.svm import SVC

# Initialize the Logistic Regression model
model_SVM = SVC(kernel='linear', C=1, tol=1e-5 , decision_function_shape='ovo',random_state=10)
fit = model_SVM.fit(X_train, np.ravel(y_train))

# Make predictions on the test set
y_pred = model_SVM.predict(X_test)

# Calculate and print accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Calculate and print macro precision
macro_precision = precision_score(y_test, y_pred, average='macro')
print("Macro Precision: {:.4f}".format(macro_precision))

# Calculate and print weighted precision
weighted_precision = precision_score(y_test, y_pred, average='weighted')
print("Weighted Precision: {:.4f}".format(weighted_precision))

# Calculate and print macro recall
macro_recall = recall_score(y_test, y_pred, average='macro')
print("Macro Recall: {:.4f}".format(macro_recall))

# Calculate and print weighted recall
weighted_recall = recall_score(y_test, y_pred, average='weighted')
print("Weighted Recall: {:.4f}".format(weighted_recall))

# Calculate and print macro F1-score
macro_f1 = f1_score(y_test, y_pred, average='macro')
print("Macro F1-Score: {:.4f}".format(macro_f1))

# Calculate and print weighted F1-score
weighted_f1 = f1_score(y_test, y_pred, average='weighted')
print("Weighted F1-Score: {:.4f}".format(weighted_f1))

# Display confusion matrix
cf_matrix = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix:")
print(cf_matrix)

# Display classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, digits=4))

Accuracy: 98.08%
Macro Precision: 0.9582
Weighted Precision: 0.9820
Macro Recall: 0.9812
Weighted Recall: 0.9808
Macro F1-Score: 0.9690
Weighted F1-Score: 0.9809

Confusion Matrix:
[[ 24   0   0   0   1]
 [  0 111   0   0   0]
 [  0   0  13   0   0]
 [  3   0   1  70   0]
 [  0   0   0   0  37]]

Classification Report:
              precision    recall  f1-score   support

           0     0.8889    0.9600    0.9231        25
           1     1.0000    1.0000    1.0000       111
           2     0.9286    1.0000    0.9630        13
           3     1.0000    0.9459    0.9722        74
           4     0.9737    1.0000    0.9867        37

    accuracy                         0.9808       260
   macro avg     0.9582    0.9812    0.9690       260
weighted avg     0.9820    0.9808    0.9809       260

